env:
  global:
    - secure: "W3PaYhPnJFCaG6TW5Xc0wtggdEqcreTQcHThmIo5Eqs/jUL2toiUiv3ZWlhzR3tkphLvt2KeaQe83BR6RTifYjSmnmAePj0Gw5res1AXzN95OsKEk3nMiTZbVP+PuTTbQZJga8B31nRUBiAMQ6FsNlpGq7E8sp9N65lnR3mGHAE="

sudo: false

addons:
  apt:
    packages:
      - graphviz

language: python

branches:
  only:
    - master

before_install:
  - pip install six sphinx sphinx_bootstrap_theme jsonschema pyyaml mistune

install:
  - make html
